name: Release

# 当 main 分支被 push,就会触发
on:
  push:
    branches: [main]
# 权限
permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 安装 nodejs
        uses: actions/setup-node@v4 # 升级到最新版
        with:
          node-version: "20.8.1" # node 版本
          cache: "pnpm" # 自动管理 pnpm 缓存

      - name: 构建 dist # 构建，根据自己的仓库构建命令来
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: 发布 npm 包
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
        run: |
          npx semantic-release
